var CACHE_NAME = 'grrds-puzzle-cache-v1.0';
var urlsToCache = [
    '../index.html',
    '../images/4inarow.svg',
    '../images/bullets0.png',
    '../images/bullets0o.png',
    '../images/bullets1.png',
    '../images/bullets1o.png',
    '../images/dice.svg',
    '../images/dummy.png',
    '../images/easy.png',
    '../images/easy_gold.png',
    '../images/hard.png',
    '../images/hard_gold.png',
    '../images/info.png',
    '../images/lock.svg',
    '../images/mail.svg',
    '../images/medal1.png',
    '../images/medal2.png',
    '../images/medal3.png',
    '../images/medium.png',
    '../images/medium_gold.png',
    '../images/next.png',
    '../images/piece_gold.png',
    '../images/prev.png',
    '../images/puzzle.svg',
    '../images/settings.png',
    '../images/title1.png',
    '../images/title_wide.png',
    '../images/america/theme.png',
    '../images/america/image-set-1/sujet1s.jpg',
    '../images/america/image-set-1/sujet2s.jpg',
    '../images/america/image-set-1/sujet3s.jpg',
    '../images/america/image-set-1/sujetp1s.jpg',
    '../images/america/image-set-1/sujetp2s.jpg',
    '../images/america/image-set-1/sujetp3s.jpg',
    '../images/america/image-set-2/sujet1s.jpg',
    '../images/america/image-set-2/sujet2s.jpg',
    '../images/america/image-set-2/sujet3s.jpg',
    '../images/america/image-set-2/sujetp1s.jpg',
    '../images/america/image-set-2/sujetp2s.jpg',
    '../images/america/image-set-2/sujetp3s.jpg',
    '../images/america/image-set-3/sujet1s.jpg',
    '../images/america/image-set-3/sujet2s.jpg',
    '../images/america/image-set-3/sujet3s.jpg',
    '../images/america/image-set-3/sujetp1s.jpg',
    '../images/america/image-set-3/sujetp2s.jpg',
    '../images/america/image-set-3/sujetp3s.jpg',
    '../images/america/image-set-4/sujet1s.jpg',
    '../images/america/image-set-4/sujet2s.jpg',
    '../images/america/image-set-4/sujet3s.jpg',
    '../images/america/image-set-4/sujetp1s.jpg',
    '../images/america/image-set-4/sujetp2s.jpg',
    '../images/america/image-set-4/sujetp3s.jpg',
    '../images/animals/theme.png',
    '../images/animals/image-set-1/sujet1s.jpg',
    '../images/animals/image-set-1/sujet2s.jpg',
    '../images/animals/image-set-1/sujet3s.jpg',
    '../images/animals/image-set-1/sujetp1s.jpg',
    '../images/animals/image-set-1/sujetp2s.jpg',
    '../images/animals/image-set-1/sujetp3s.jpg',
    '../images/animals/image-set-2/sujet1s.jpg',
    '../images/animals/image-set-2/sujet2s.jpg',
    '../images/animals/image-set-2/sujet3s.jpg',
    '../images/animals/image-set-2/sujetp1s.jpg',
    '../images/animals/image-set-2/sujetp2s.jpg',
    '../images/animals/image-set-2/sujetp3s.jpg',
    '../images/animals/image-set-3/sujet1s.jpg',
    '../images/animals/image-set-3/sujet2s.jpg',
    '../images/animals/image-set-3/sujet3s.jpg',
    '../images/animals/image-set-3/sujetp1s.jpg',
    '../images/animals/image-set-3/sujetp2s.jpg',
    '../images/animals/image-set-3/sujetp3s.jpg',
    '../images/animals/image-set-4/sujet1s.jpg',
    '../images/animals/image-set-4/sujet2s.jpg',
    '../images/animals/image-set-4/sujet3s.jpg',
    '../images/animals/image-set-4/sujetp1s.jpg',
    '../images/animals/image-set-4/sujetp2s.jpg',
    '../images/animals/image-set-4/sujetp3s.jpg',
    '../images/asia/theme.png',
    '../images/asia/image-set-1/sujet1s.jpg',
    '../images/asia/image-set-1/sujet2s.jpg',
    '../images/asia/image-set-1/sujet3s.jpg',
    '../images/asia/image-set-1/sujetp1s.jpg',
    '../images/asia/image-set-1/sujetp2s.jpg',
    '../images/asia/image-set-1/sujetp3s.jpg',
    '../images/asia/image-set-2/sujet1s.jpg',
    '../images/asia/image-set-2/sujet2s.jpg',
    '../images/asia/image-set-2/sujet3s.jpg',
    '../images/asia/image-set-2/sujetp1s.jpg',
    '../images/asia/image-set-2/sujetp2s.jpg',
    '../images/asia/image-set-2/sujetp3s.jpg',
    '../images/asia/image-set-3/sujet1s.jpg',
    '../images/asia/image-set-3/sujet2s.jpg',
    '../images/asia/image-set-3/sujet3s.jpg',
    '../images/asia/image-set-3/sujetp1s.jpg',
    '../images/asia/image-set-3/sujetp2s.jpg',
    '../images/asia/image-set-3/sujetp3s.jpg',
    '../images/asia/image-set-4/sujet1s.jpg',
    '../images/asia/image-set-4/sujet2s.jpg',
    '../images/asia/image-set-4/sujet3s.jpg',
    '../images/asia/image-set-4/sujetp1s.jpg',
    '../images/asia/image-set-4/sujetp2s.jpg',
    '../images/asia/image-set-4/sujetp3s.jpg',
    '../images/europe/theme.png',
    '../images/europe/image-set-1/sujet1s.jpg',
    '../images/europe/image-set-1/sujet2s.jpg',
    '../images/europe/image-set-1/sujet3s.jpg',
    '../images/europe/image-set-1/sujetp1s.jpg',
    '../images/europe/image-set-1/sujetp2s.jpg',
    '../images/europe/image-set-1/sujetp3s.jpg',
    '../images/europe/image-set-2/sujet1s.jpg',
    '../images/europe/image-set-2/sujet2s.jpg',
    '../images/europe/image-set-2/sujet3s.jpg',
    '../images/europe/image-set-2/sujetp1s.jpg',
    '../images/europe/image-set-2/sujetp2s.jpg',
    '../images/europe/image-set-2/sujetp3s.jpg',
    '../images/europe/image-set-3/sujet1s.jpg',
    '../images/europe/image-set-3/sujet2s.jpg',
    '../images/europe/image-set-3/sujet3s.jpg',
    '../images/europe/image-set-3/sujetp1s.jpg',
    '../images/europe/image-set-3/sujetp2s.jpg',
    '../images/europe/image-set-3/sujetp3s.jpg',
    '../images/europe/image-set-4/sujet1s.jpg',
    '../images/europe/image-set-4/sujet2s.jpg',
    '../images/europe/image-set-4/sujet3s.jpg',
    '../images/europe/image-set-4/sujetp1s.jpg',
    '../images/europe/image-set-4/sujetp2s.jpg',
    '../images/europe/image-set-4/sujetp3s.jpg',
    '../images/flowers/theme.png',
    '../images/flowers/image-set-1/sujet1s.jpg',
    '../images/flowers/image-set-1/sujet2s.jpg',
    '../images/flowers/image-set-1/sujet3s.jpg',
    '../images/flowers/image-set-1/sujetp1s.jpg',
    '../images/flowers/image-set-1/sujetp2s.jpg',
    '../images/flowers/image-set-1/sujetp3s.jpg',
    '../images/flowers/image-set-2/sujet1s.jpg',
    '../images/flowers/image-set-2/sujet2s.jpg',
    '../images/flowers/image-set-2/sujet3s.jpg',
    '../images/flowers/image-set-2/sujetp1s.jpg',
    '../images/flowers/image-set-2/sujetp2s.jpg',
    '../images/flowers/image-set-2/sujetp3s.jpg',
    '../images/flowers/image-set-3/sujet1s.jpg',
    '../images/flowers/image-set-3/sujet2s.jpg',
    '../images/flowers/image-set-3/sujet3s.jpg',
    '../images/flowers/image-set-3/sujetp1s.jpg',
    '../images/flowers/image-set-3/sujetp2s.jpg',
    '../images/flowers/image-set-3/sujetp3s.jpg',
    '../images/flowers/image-set-4/sujet1s.jpg',
    '../images/flowers/image-set-4/sujet2s.jpg',
    '../images/flowers/image-set-4/sujet3s.jpg',
    '../images/flowers/image-set-4/sujetp1s.jpg',
    '../images/flowers/image-set-4/sujetp2s.jpg',
    '../images/flowers/image-set-4/sujetp3s.jpg',
    '../images/tricky/theme.png',
    '../images/tricky/image-set-1/sujet1s.jpg',
    '../images/tricky/image-set-1/sujet2s.jpg',
    '../images/tricky/image-set-1/sujet3s.jpg',
    '../images/tricky/image-set-1/sujetp1s.jpg',
    '../images/tricky/image-set-1/sujetp2s.jpg',
    '../images/tricky/image-set-1/sujetp3s.jpg',
    '../images/tricky/image-set-2/sujet1s.jpg',
    '../images/tricky/image-set-2/sujet2s.jpg',
    '../images/tricky/image-set-2/sujet3s.jpg',
    '../images/tricky/image-set-2/sujetp1s.jpg',
    '../images/tricky/image-set-2/sujetp2s.jpg',
    '../images/tricky/image-set-2/sujetp3s.jpg',
    '../images/tricky/image-set-3/sujet1s.jpg',
    '../images/tricky/image-set-3/sujet2s.jpg',
    '../images/tricky/image-set-3/sujet3s.jpg',
    '../images/tricky/image-set-3/sujetp1s.jpg',
    '../images/tricky/image-set-3/sujetp2s.jpg',
    '../images/tricky/image-set-3/sujetp3s.jpg',
    '../images/tricky/image-set-4/sujet1s.jpg',
    '../images/tricky/image-set-4/sujet2s.jpg',
    '../images/tricky/image-set-4/sujet3s.jpg',
    '../images/tricky/image-set-4/sujetp1s.jpg',
    '../images/tricky/image-set-4/sujetp2s.jpg',
    '../images/tricky/image-set-4/sujetp3s.jpg',
    'binaryajax.js',
    'exif.js',
    'jquery.mobile-1.3.2.min.css',
    'jquery.mobile-1.3.2.min.js',
    'jquery-1.9.1.min.js',
    'kinetic-v4.7.4.min.js',
    'l10n.js',
    'puzzle.css',
    'puzzle.js',
    'sw.js',
    'swipe.css',
    'swipe.js',
    'images/ajax-loader.gif',
    'images/ajax-loader.png',
    'images/icons-18-black.png',
    'images/icons-18-white.png',
    'images/icons-36-black.png',
    'images/icons-36-white.png',
    '../Locales/ar/puzzle.properties',
    '../Locales/bn/puzzle.properties',
    '../Locales/cs/puzzle.properties',
    '../Locales/de/puzzle.properties',
    '../Locales/en/puzzle.properties',
    '../Locales/es/puzzle.properties',
    '../Locales/fr/puzzle.properties',
    '../Locales/hr/puzzle.properties',
    '../Locales/hu/puzzle.properties',
    '../Locales/it/puzzle.properties',
    '../Locales/nl/puzzle.properties',
    '../Locales/pl/puzzle.properties',
    '../Locales/pt_BR/puzzle.properties',
    '../Locales/pt_PT/puzzle.properties',
    '../Locales/rm/puzzle.properties',
    '../Locales/ru/puzzle.properties',
    '../Locales/sl/puzzle.properties',
    '../Locales/sr/puzzle.properties',
    '../Locales/ta/puzzle.properties',
    '../Locales/tr/puzzle.properties',
    '../Locales/ur/puzzle.properties',
    '../Locales/zh/puzzle.properties',
    '../Locales/zh_CN/puzzle.properties',
    '../Locales/locales.ini',
    '../Sounds/click.mp3',
    '../Sounds/click.ogg',
    '../Sounds/ding.mp3',
    '../Sounds/ding.ogg'
];

self.addEventListener('install', function(event) {
    // Perform install steps
    event.waitUntil(
        caches.open(CACHE_NAME)
            .then(function(cache) {
                console.log('Opened cache');
                return cache.addAll(urlsToCache);
            })
    );
});

self.addEventListener('fetch', function(event) {
    event.respondWith(
        caches.match(event.request)
            .then(function(response) {
                // Cache hit - return response
                if (response) {
                    return response;
                }

                var fetchRequest = event.request.clone();

                return fetch(fetchRequest).then(
                    function(response) {
                        // Check if we received a valid response
                        if(!response || response.status !== 200 || response.type !== 'basic') {
                            return response;
                        }

                        var responseToCache = response.clone();

                        caches.open(CACHE_NAME)
                            .then(function(cache) {
                                cache.put(event.request, responseToCache);
                            });

                        return response;
                    }
                );
            })
    );
});